version: '3.3'
services:
  pgdb:
    image: postgres
    environment:
#      POSTGRES_DB: global_library
      POSTGRES_MULTIPLE_DATABASES: global_library, extension_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
    volumes:
          - pg_data:/var/lib/postgresql
  web:
    build:
      context: app-rest
    depends_on:
      - pgdb
    image: tomcat:9.0
    volumes:
      - ./target/app-rest.war:/usr/local/tomcat/webapps/app-rest.war
    ports:
      - '8080:8080'
    environment:
      POSTGRES_DB: global_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
volumes:
  pg_data: